# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

include:
  - project: 'nitrokey/gitlab-ci'
    file:
      - 'common-jobs/common_jobs.yml'

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  SCRIPTS_REPO: git@git.nitrokey.com:nitrokey/gitlab-ci.git
  REPO_GROUP: nitrokey
  REPO_NAME: nitrokey-hardware-test
  MAIN_BRANCH: main
  COMMON_UPLOAD_NIGHTLY: "false"
  COMMON_GITHUB_RELEASE: "false"
  COMMON_UPLOAD_FILES: "false"
  COMMON_UPDATE_DOCKER: "false"
  COMMON_UPLOAD_OEM_FILES: "false"


stages:          # List of stages for jobs, and their order of execution
  - pull-github
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  tags:
    - docker
  variables:
  script:
    - apt update && apt install -qy make
    - make ci-setup-ubuntu
    - make check
  before_script: []
  after_script: []

#hw-test-job:   # This job runs in the test stage.
#  tags:
#    - nk3-hw
#  stage: test    # It only starts when the job in the build stage completes successfully.
#  script:
#    - make ci
#  artifacts:
#      paths:
#        - artifacts/
#deploy-job:      # This job runs in the deploy stage.
#  tags:
#    - nk3-hw
#  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#  environment: production
#  script:
#    - echo "Deploying application..."
#    - echo "Application successfully deployed."
