device = "nk3"
variant = "nrf52"
provisioner_firmware = "../artifacts/provisioner-nrf52.hex"
application_firmware = "../artifacts/firmware-nrf52.hex"
mbr = "./config/nrf52/mbr.hex"
bootloader = "./config/nrf52/bootloader.hex"
bootloader_key = "../utils/test-certificates/firmware-nk3am/dfu_private.key"
fido_key_path= "../utils/test-certificates/fido/nk-fido-ca-key.trussed"
fido_certificate_path= "../utils/test-certificates/fido/nk-fido-ee-cert.der"

device_id = ""
firmware_version = ""
usb_manager_enabled = true
output = "artifacts/"
ykush_port_device = 1
ykush_port_debug_adapter = 2
ykush_serial_number = "Y3N11073"

test_fido2 = true
test_secrets = true
test_opcard = true
